### ISSUE TITLE
Avoid immediate duplicate positions in queue when a dequeue occurs

### ISSUE THREAD

**Issue by esigler** [esigler/lita-locker#41]
Avoid the following:

```
A: !lock foo
B: !lock foo
C: !lock foo
B: !lock foo
C: !locker dequeue foo

End result: foo: locked by A, queue: B, B
```

There is some duplicate protection logic, but it may not guard against the case where someone dequeues out from the middle of a pairing.

**Comment by tristaneuan** [comment]
Addressed in PR #43 and released in v1.0.3
