### ISSUE TITLE
Allow for a lock owner to transfer a lock to someone else

### ISSUE THREAD

**Issue by esigler** [esigler/lita-locker#42]
A lock owner sometimes needs to transfer a lock.  Possible syntax could be:

```
!give artemis production to username
```

Thoughts:

* This should probably have the same behavior as !steal - avoid queue manipulation altogether.
* This wouldn't enable too much abuse, since if two people conspired to keep a lock, a 3rd person could still steal it.

**Comment by tristaneuan** [comment]
Addressed in PR #44, merged, and released as v1.0.4.
